language: php

php:
  - 7.0

env:
  global:
    - DB_CONNECTION=sqlite

install:
  - composer install --optimize-autoloader --quiet
  - npm install newman --global

script:
  - newman --version
  - php artisan serve &
  - sleep 5
  - newman run tests/postman/GraphQL.postman_collection.json
