language: php

php:
  - 7.0
  
env:
  global:
    - DB_CONNECTION=sqlite
    - NODE_VERSION=8.2.1
    - YARN_VERSION=0.27.5

before_install:
  - nvm i $NODE_VERSION
  - export PATH="$HOME/.yarn/bin:$PATH"
  - |
    if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    fi

install:
  - composer install --optimize-autoloader --quiet
  - yarn install --pure-lockfile

before_script:
  - node --version
  - npm --version
  - yarn --version
  - php -v
  - node_modules/.bin/newman --version

script:
  - php artisan serve &
  - ./tasks/wait-for-server.sh
  - node_modules/.bin/newman run tests/postman/GraphQL.postman_collection.json

cache:
  yarn: true
  directories:
    - $HOME/.yarn
    - node_modules
    - vendor
    - $HOME/.composer
